### ISSUE TITLE
Use without wire.h possible?

### ISSUE THREAD

**Issue by Cysign** [DFRobot/DFRobot_LIS2DH12#1]
Hi,
I wonder how to modify this lib to work without wire.h - so it would be easy to use it on different plattforms than Arduino.

**Comment by ouki-wang** [comment]
@Cysign
You need to learn iic protocol. porting the driver library on other mcu platforms is not a difficult work.

**Comment by tangjie133** [comment]
Please transfer to new library https://github.com/DFRobot/DFRobot_LIS
