### ISSUE TITLE
The Wire.requestFrom() should not be followed by a Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [DFRobot/DFRobot_LIS2DH12#3]
In the file "DFRobot_LIS2DH12/DFRobot_LIS2DH12.cpp" the Wire.endTransmission() is followed by a Wire.endTransmission(). Those Wire.endTransmission() can be removed.
Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2).

It might be a good idea to rewrite the function "readReg()" and keep writing and reading together.

**Comment by wxzed** [comment]
@Koepel Thank you very much for your feedback, I have modified the library file
