### ISSUE TITLE
Support interrupts 

### ISSUE THREAD

**Issue by Lux90** [DFRobot/DFRobot_LIS2DH12#5]
According to the LIS2DH datasheet: 
"The LIS2DH may also be configured to generate an inertial Wake-Up and Free-Fall interrupt signal accordingly to a programmed acceleration event along the enabled axes. Both FreeFall and Wake-Up can be available simultaneously on two different pins." 

Is it possible to add this functionality to the library?

**Comment by tangjie133** [comment]
Please transfer to new library https://github.com/DFRobot/DFRobot_LIS
